  MD001: false
  MD002: true
  MD003: false
  # 列表样式是 设置为破折号(dash)
  MD004: 
    style: dash
  MD005: false
  MD006:
    ul_single: true
    ol_single: true
  MD007:
    indent: 4
  MD009:
    br_spaces: 2
  MD010: true


  MD013:
    line_length: 120
  MD018: true
  MD019: false
  MD020: false

  MD026: true

  MD029: true
  MD030: false
  MD033: false
  MD036: false

